### ISSUE TITLE
登录后获取用户信息等报错！

### ISSUE THREAD

**Issue by lvtao-net** [qiqiaobin/Gin-Vue3-Admin#1]
咧？？？ 你跑起来的时候，不会报  recover.go:18: panic: runtime error: invalid memory address or nil pointer dereference 错误吗？
macOS下  go 1.21.0版本
```log

21:53:52 app         | [GIN] 2023/08/27 - 21:53:52 | 200 |    1.691672ms |             ::1 | POST     "/system/auth/login"
21:53:52 app         | 获取 token 中的 claims
21:53:52 app         | &{2 admin 管理员 0 { 1693230832  1693144432 gin-vue3-admin 0 admin}}
21:53:52 app         | &{2 admin 管理员 0 { 1693230832  1693144432 gin-vue3-admin 0 admin}}
true
true
&{2 admin 管理员 0 { 1693230832  1693144432 gin-vue3-admin 0 admin}}
true
true
21:53:52 app         | 2023/08/27 21:53:52 recover.go:18: panic: runtime error: invalid memory address or nil pointer dereference

```

其中登录是OK的，登录后获取userInfo等一系列就会提示500错误
```json

{
    "code": 500,
    "success": false,
    "data": null,
    "message": "runtime error: invalid memory address or nil pointer dereference"
}

```

错误详情：
```

21:53:52 app         | goroutine 9 [running]:
runtime/debug.Stack()
	/usr/local/Cellar/go/1.21.0/libexec/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.21.0/libexec/src/runtime/debug/stack.go:16 +0x13
tadmin/middleware.Recover.func1()
	/Volumes/dev/golang/Gin-Vue3-Admin-main/tadmin/middleware/recover.go:19 +0xbf
panic({0x19e4ea0?, 0x30b98c0?})
	/usr/local/Cellar/go/1.21.0/libexec/src/runtime/panic.go:914 +0x21f
tadmin/pkg/cache.(*RedisTool).Get(0x1, {0xc000e224b0, 0x15}, {0x19798c0, 0xc0007f6d38})
	/Volumes/dev/golang/Gin-Vue3-Admin-main/tadmin/pkg/cache/redis.go:54 +0x6a
tadmin/service.GetUserPermission(0x270000c00099d5e8?)
	/Volumes/dev/golang/Gin-Vue3-Admin-main/tadmin/service/sys_auth.go:98 +0x85
tadmin/router.InitRouters.Casbin.func3(0xc000e14e00)
	/Volumes/dev/golang/Gin-Vue3-Admin-main/tadmin/middleware/casbin.go:34 +0x3d
github.com/gin-gonic/gin.(*Context).Next(0xc000e14e00)
	/Users/memory/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
tadmin/router.InitRouters.JwtAuth.func2(0xc000e14e00)
	/Volumes/dev/golang/Gin-Vue3-Admin-main/tadmin/middleware/jwt_auth.go:45 +0x111
github.com/gin-gonic/gin.(*Context).Next(0xc000e14e00)
	/Users/memory/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
tadmin/router.InitRouters.Cors.func1(0xc000e14e00)
	/Volumes/dev/golang/Gin-Vue3-Admin-main/tadmin/middleware/cors.go:22 +0x110
github.com/gin-gonic/gin.(*Context).Next(...)
	/Users/memory/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
tadmin/middleware.Recover(0xc000e14e00)
	/Volumes/dev/golang/Gin-Vue3-Admin-main/tadmin/middleware/recover.go:26 +0x62
github.com/gin-gonic/gin.(*Context).Next(...)
	/Users/memory/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1(0xc000e14e00)
	/Users/memory/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 +0x7a
github.com/gin-gonic/gin.(*Context).Next(...)
	/Users/memory/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc000e14e00)
	/Users/memory/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 +0xde
github.com/gin-gonic/gin.(*Context).Next(...)
	/Users/memory/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0007c91e0, 0xc000e14e00)
	/Users/memory/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 +0x65b
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0007c91e0, {0x2214860?, 0xc0001bcb60}, 0xc000e15100)
	/Users/memory/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x1dd
net/http.serverHandler.ServeHTTP({0xc000ab14a0?}, {0x2214860?, 0xc0001bcb60?}, 0x6?)
	/usr/local/Cellar/go/1.21.0/libexec/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0001f4360, {0x22172e8, 0xc000ab13b0})
	/usr/local/Cellar/go/1.21.0/libexec/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 55
	/usr/local/Cellar/go/1.21.0/libexec/src/net/http/server.go:3086 +0x5cb
21:53:52 app         | [GIN] 2023/08/27 - 21:53:52 | 200 |     560.776µs |             ::1 | GET      "/system/auth/userInfo"

```

**Comment by qiqiaobin** [comment]
你是用什么用户登录的？你可以用superadmin用户跳过获取权限菜单这步，我还在修改代码，准备把菜单放到前端去管理，后端只管理权限路由

**Comment by qiqiaobin** [comment]
我已经更新代码了，这次更新重构了用户管理、角色管理模块，下一步计划把菜单路由放到前端，代码在本地跑是没有问题的，你上次没跑通可能是我忘记更新最新的SQL文件，这次SQL文件也一起更新了
